### ISSUE TITLE
Build fails after 33c1e70

### ISSUE THREAD

**Issue by savchenko** [foxcpp/mailsec-check#6]
`go build` returns the following error:

```
# github.com/foxcpp/mailsec-check/mtasts
mtasts/mtasts.go:85:24: undefined: io.ReadAll
```

The issue seems to be here:

```patch
diff --git a/mtasts/mtasts.go b/mtasts/mtasts.go
index 9ad09ec..676c4fb 100644
--- a/mtasts/mtasts.go
+++ b/mtasts/mtasts.go
@@ -4,6 +4,7 @@ package mtasts
 
 import (
 	"bufio"
+	"bytes"
 	"fmt"
 	"io"
 	"strconv"
@@ -80,8 +81,14 @@ type Policy struct {
 	MX     []string
 }
 
-func readPolicy(contents io.Reader) (*Policy, error) {
-	scnr := bufio.NewScanner(contents)
+func readPolicy(contents io.Reader) (*Policy, string, error) {
+	contentsBytes, err := io.ReadAll(contents)
+	if err != nil {
+		return nil, "", err
+	}
+	rawContents := string(contentsBytes)
+	contentsReader := bytes.NewReader(contentsBytes)
+	scnr := bufio.NewScanner(contentsReader)
 	policy := Policy{}
 
 	present := make(map[string]struct{})
```

**Comment by foxcpp** [comment]
Go 1.16 or newer is required
